### ISSUE TITLE
axios@0.19.2 security issue

### ISSUE THREAD

**Issue by yoiang** [node-red/node-red-admin#14]
Hello! I have Dependabot enabled on my [contrib](https://github.com/Adorkable/node-red-contrib-ui-led) repo and it has flagged the current version of **axios** that **node-red-admin** requires as having a severe security issue! It would be great to move to a newer version.

Flagged issue: https://github.com/Adorkable/node-red-contrib-ui-led/security/dependabot/yarn.lock/axios/open

### What are the steps to reproduce?
Install **node-red**. 

### What happens?
**node-red**@1.2.6 requires **node-red-admin**@^0.2.6. **node-red-admin**@0.2.6 requires **axios**@0.19.2. 

### What do you expect to happen?
As per Dependabot's recommendation **node-red-admin** should require a version of **axios** where this issue has been fixed, according to the tool at least **axios**@0.21.1.

**Comment by knolleary** [comment]
Hi - yes, we have #13 to address this. Just need to get it merged and published.

**Comment by knolleary** [comment]
`node-red-admin@0.2.7` now published with the fix
