### ISSUE TITLE
userDir issues

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red-admin#4]
Hi Nick,

Couple of possible minor issues with this utility.

The user directory is picked up from environment variables:
`process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE`
This would return the users home directory but the Node-Red userDir might not be there.

The actual folder is hard coded as `.node-red` which again is not necessarily correct.

Both the path and the folder can be changed in settings so shouldn't the whole thing be customisable? Or have I missed something?

Might it not be better to pick up a single environment override such as `NRUSERDIR` to be able to directly specify the userDir?

**Comment by knolleary** [comment]
The directory it uses to store its configuration does not need to be a node-red instance's userDir. By default it picks what is likely to be a node-red userDir (assuming node-red is running on the local machine - but again, nothing requires that).

I can see it might be useful to be able to override the userDir - particularly if you have multiple instances to administer, each with its own auth settings.

**Comment by TotallyInformation** [comment]
Oh, OK. Thanks for clarifying, I'd assumed it needed the correct userDir to operate. If it is indeed only for storing the admin tool's config then it is slightly less of a problem. However, as you say, it would still be useful if you could have different configs. I'm guessing not so many people run multiple instances on the same machine.

I can always control it from a script. Or more likely from an npm script. So you could do something like `npm run nr-inst node-red-contrib-xxxxx` and it would run the appropriate admin command against that instance.

**Comment by knolleary** [comment]
0.2.0 release adds the `--userDir` option to specify a custom location for the config file.
